import { readFileSync, readdirSync } from 'node:fs';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * What this repository trusts to run in CI, and how tightly it is named.
 *
 * A GitHub Action referenced by tag runs whatever that tag currently points at.
 * Tags are mutable and moving one is a single API call for anyone who gains
 * write access to the action's repository — which is how `tj-actions/changed-files`
 * became a credential exfiltrator across thousands of repositories in March 2025
 * without any of them changing a line. A commit SHA cannot be re-pointed.
 *
 * This matters more here than in most repositories: `publish.yml` holds an
 * Entra federated credential that can publish to the Marketplace under this
 * publisher's name. An action running in that job is running with the ability
 * to ship a release.
 */

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const WORKFLOWS = path.join(REPO_ROOT, '.github', 'workflows');

const USES = /^\s*-?\s*uses:\s*(\S+)/;
/** 40 hex characters. A tag, branch or short SHA is not this. */
const SHA_PINNED = /@[0-9a-f]{40}$/;
/** A local composite action, which lives in this repository and needs no pin. */
const LOCAL_ACTION = /^\.{1,2}\//;

function workflowFiles(): string[] {
  return readdirSync(WORKFLOWS)
    .filter(name => name.endsWith('.yml') || name.endsWith('.yaml'))
    .map(name => path.join(WORKFLOWS, name));
}

function actionReferences(): Array<{ workflow: string; line: number; ref: string }> {
  return workflowFiles().flatMap(file =>
    readFileSync(file, 'utf8').split(/\r?\n/).flatMap((text, index) => {
      const ref = USES.exec(text)?.[1];
      if (!ref || LOCAL_ACTION.test(ref)) { return []; }
      return [{ workflow: path.basename(file), line: index + 1, ref }];
    }),
  );
}

describe('every third-party action is pinned to a commit', () => {
  it('found actions to check, rather than passing because the scan is broken', () => {
    expect(actionReferences().length).toBeGreaterThan(0);
  });

  it('has no action referenced by a mutable tag', () => {
    const mutable = actionReferences()
      .filter(entry => !SHA_PINNED.test(entry.ref))
      .map(entry => `${entry.workflow}:${entry.line} — ${entry.ref}`)
      .sort();

    expect(
      mutable,
      'Pin these to a full 40-character commit SHA with the version in a trailing comment. '
      + 'A tag is mutable: whoever can move it decides what runs in a job that can publish this extension.',
    ).toEqual([]);
  });

  it('keeps the human-readable version beside each pin', () => {
    // A bare SHA is unreviewable — nobody can tell v4 from v7 by looking, so
    // upgrades stop happening and the pin becomes a way of staying old rather
    // than a way of staying deliberate.
    //
    // Either position counts. `trusted-local-ci.yml` is generated by
    // `trustedLocalCiStarter.ts`, which writes the release note on the line
    // *above* the pin and then validates the file back byte-for-byte — so a
    // trailing comment added here would make the scaffolder reject its own
    // output. The requirement is that a reviewer can see the version, not
    // where the character sits.
    const undocumented = workflowFiles().flatMap(file => {
      const lines = readFileSync(file, 'utf8').split(/\r?\n/);
      return lines.flatMap((text, index) => {
        const ref = USES.exec(text)?.[1];
        if (!ref || LOCAL_ACTION.test(ref) || !SHA_PINNED.test(ref)) { return []; }
        const documented = /#\s*v?\d/.test(text) || /#\s*v?\d/.test(lines[index - 1] ?? '');
        return documented ? [] : [`${path.basename(file)}:${index + 1}`];
      });
    });

    expect(
      undocumented,
      'Add a `# v<major>` comment on the `uses:` line or the line above it, so the pin can be reviewed.',
    ).toEqual([]);
  });
});

describe('the runtime dependency surface stays small and known', () => {
  const manifest = JSON.parse(readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf8')) as {
    dependencies?: Record<string, string>;
  };

  /**
   * Everything shipped inside the `.vsix`, with why it is there.
   *
   * A ratchet on the *set*, not a count: a new runtime dependency is code that
   * runs on a user's machine with the extension host's privileges, and adding
   * one should be a decision somebody defends in review rather than a line in a
   * lockfile diff. Removing one needs no permission.
   */
  const DECLARED: Readonly<Record<string, string>> = {
    '@agentclientprotocol/sdk': 'ACP client — subscription-backed model capacity.',
    '@modelcontextprotocol/sdk': 'MCP client — external tool servers.',
    '@noble/secp256k1': 'BIP-340 Schnorr signing for Nostr NIP-42. Chosen over @noble/curves: 170 KB, zero transitive dependencies.',
    mysql2: 'Lens database reader (MySQL).',
    pg: 'Lens database reader (PostgreSQL).',
    ws: 'WebSocket transport for the Buzz relay.',
    zod: 'Schema validation at untrusted boundaries.',
  };

  it('ships nothing undeclared', () => {
    const undeclared = Object.keys(manifest.dependencies ?? {})
      .filter(name => !(name in DECLARED))
      .sort();

    expect(
      undeclared,
      'A new runtime dependency runs on the user\'s machine with the extension host\'s privileges. '
      + 'Add it to DECLARED with the reason it is worth that.',
    ).toEqual([]);
  });

  it('declares nothing it no longer ships', () => {
    const stale = Object.keys(DECLARED)
      .filter(name => !(name in (manifest.dependencies ?? {})))
      .sort();

    expect(stale, 'A declared dependency is gone. Remove it from DECLARED.').toEqual([]);
  });
});
