import { readFileSync } from 'node:fs';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  deriveTurnCapabilityEnvelope,
  intersectTurnCapabilities,
  isToolAllowedByTurnEnvelope,
} from '../../src/core/orchestrator.ts';

/**
 * Whether a turn's read-only choice survives into the work it authorised.
 *
 * It did not. `processTaskWithAgent` derives the envelope from
 * `request.userMessage`, and a subtask's "message" is generated by the planner
 * — it describes the job, not the limits somebody put on it. So a read-only
 * `/project` run derived a **permissive** envelope for every subtask, and the
 * restriction applied to precisely the turn that did no work.
 *
 * This is the same failure `agentHandoff` was built to prevent for skills:
 * authority accumulating across a hand-off, where the route past a restriction
 * is to ask something else to do the job.
 */

const REPO_ROOT = path.resolve(__dirname, '..', '..');

/** What a user types when they mean it. */
const READ_ONLY_REQUEST = 'Audit the auth module for security issues. Read-only — do not change anything.';
/** What the planner then generates for one step of that work. */
const PLANNER_SUBTASK_TEXT = 'Implement the token refresh fix in src/auth/session.ts and update its tests.';

describe('a restriction is inherited, never re-derived away', () => {
  it('is lost if the subtask derives its own envelope — the bug', () => {
    // Kept as a positive assertion about the *old* behaviour, so the reason
    // for the intersection cannot be mistaken for caution.
    const asSubtaskWouldHaveDerived = deriveTurnCapabilityEnvelope(PLANNER_SUBTASK_TEXT);

    expect(asSubtaskWouldHaveDerived.writesAllowed).toBe(true);
    expect(asSubtaskWouldHaveDerived.commandsAllowed).toBe(true);
  });

  it('survives when the caller passes it down', () => {
    const authorised = deriveTurnCapabilityEnvelope(READ_ONLY_REQUEST);
    expect(authorised.writesAllowed, 'the request itself must read as read-only').toBe(false);

    const inSubtask = intersectTurnCapabilities(
      deriveTurnCapabilityEnvelope(PLANNER_SUBTASK_TEXT),
      authorised,
    );

    expect(inSubtask.writesAllowed).toBe(false);
    expect(isToolAllowedByTurnEnvelope('file-write', {}, inSubtask)).toBe(false);
    expect(isToolAllowedByTurnEnvelope('file-read', {}, inSubtask)).toBe(true);
  });

  it('narrows and never widens, whichever side is stricter', () => {
    const permissive = { writesAllowed: true, commandsAllowed: true };
    const noWrites = { writesAllowed: false, commandsAllowed: true, reason: 'workspace writes are disabled' };
    const noCommands = { writesAllowed: true, commandsAllowed: false, reason: 'terminal disabled' };

    // Inherited restriction, permissive local text.
    expect(intersectTurnCapabilities(permissive, noWrites).writesAllowed).toBe(false);
    // Permissive inheritance cannot restore what the local text removed.
    expect(intersectTurnCapabilities(noWrites, permissive).writesAllowed).toBe(false);
    // Two different restrictions compose.
    const both = intersectTurnCapabilities(noCommands, noWrites);
    expect(both.writesAllowed).toBe(false);
    expect(both.commandsAllowed).toBe(false);
  });

  it('leaves an ordinary turn alone when there is nothing to inherit', () => {
    // A chat turn inherits nothing. Treating absence as a restriction would
    // deny every tool on every turn, which is how a safety feature gets
    // removed rather than fixed.
    const derived = deriveTurnCapabilityEnvelope('Fix the failing test in cartTotals.spec.ts');

    expect(intersectTurnCapabilities(derived, undefined)).toEqual(derived);
    expect(intersectTurnCapabilities(derived, undefined).writesAllowed).toBe(true);
  });

  it('keeps both reasons, de-duplicated', () => {
    const same = { writesAllowed: false, commandsAllowed: true, reason: 'workspace writes are disabled' };

    expect(intersectTurnCapabilities(same, same).reason).toBe('workspace writes are disabled');
    expect(
      intersectTurnCapabilities(
        { writesAllowed: true, commandsAllowed: false, reason: 'commands off' },
        { writesAllowed: false, commandsAllowed: true, reason: 'writes off' },
      ).reason,
    ).toBe('writes off; commands off');
  });
});

describe('an absent envelope allows everything, so every path must supply one', () => {
  it('allows a write when no envelope is present', () => {
    // Documented rather than changed: most turns have no restriction, and
    // fail-closed here would deny every tool on every ordinary turn. The
    // safety therefore depends on every path *deriving* an envelope, which is
    // what the source check below asserts.
    expect(isToolAllowedByTurnEnvelope('file-write', {}, undefined)).toBe(true);
  });

  it('is supplied by every subtask entry point', () => {
    // Asserted against the source because both entry points need a live
    // planner, a scheduler and a provider to reach. The property is that
    // neither calls `executeSubTask` without passing capabilities down.
    const source = readFileSync(path.join(REPO_ROOT, 'src', 'core', 'orchestrator.ts'), 'utf8');

    const callSites = [...source.matchAll(/await this\.executeSubTask\(([\s\S]*?)\);/g)]
      .map(match => match[1] ?? '');

    expect(callSites.length, 'No executeSubTask call sites found — this check has stopped working.')
      .toBeGreaterThan(0);

    const unpropagated = callSites.filter(args => !/Capabilities/.test(args));
    expect(
      unpropagated,
      'A subtask is being run without inheriting the authorising turn\'s capability envelope. '
      + 'It will re-derive one from planner-generated text and get a clean slate.',
    ).toEqual([]);
  });

  it('derives from the goal in both planning entry points', () => {
    const source = readFileSync(path.join(REPO_ROOT, 'src', 'core', 'orchestrator.ts'), 'utf8');
    const derivations = source.match(/const \w*[Cc]apabilities = deriveTurnCapabilityEnvelope\(/g) ?? [];

    expect(
      derivations.length,
      'Both `processProject` and `processTaskMultiStep` must derive an envelope from the user\'s own text.',
    ).toBeGreaterThanOrEqual(2);
  });
});
