/**
 * Planning the install of an ACP agent — including the runtime it needs.
 *
 * "Install it with `npm install -g …`" is only useful advice if you have npm.
 * A novice reaching ACP through "use the Claude subscription I already pay for"
 * has no reason to have Node, and telling them to install an adapter with a
 * tool they do not have is a dead end dressed as an instruction.
 *
 * This plans the whole chain — runtime first, then the agent — and hands the
 * caller a list of commands to confirm. It is the same shape
 * `src/mcp/mcpRuntime.ts` already uses for MCP stdio runtimes, and deliberately
 * so: that pattern is the project's settled answer to "may AtlasMind install
 * something", and the answer is *only after showing exactly what will run and
 * being told yes*.
 *
 * Three properties make that answer safe, and all three are load-bearing:
 *
 * 1. **Every command is code-authored.** The argv below is a constant in this
 *    file. Nothing is parsed out of a documentation page, generated by a model,
 *    or assembled from a settings string. A command derived from fetched text
 *    and then executed is remote code execution with extra steps —
 *    `buzzDocsSource.ts` treats fetched commands as quoted suggestions AtlasMind
 *    never runs, and the same line holds here.
 * 2. **No shell.** Steps are `execFile(command, args)`, never a script and never
 *    a string passed through `sh -c`, so there is no interpolation to escape.
 * 3. **Planning performs nothing.** `planAcpAgentInstall` only inspects and
 *    returns; execution is a separate call the caller makes after confirmation.
 *
 * Pure apart from the injected probe, so every branch is unit-tested.
 */

import { existsSync } from 'node:fs';
import { buildRuntimeInstallInvocation, execFileAsync } from '../mcp/mcpRuntime.js';
import type { RecommendedRuntimePackageManager, SupportedRuntimePlatform } from '../constants.js';

/** One command AtlasMind proposes to run, shown verbatim before anything runs. */
export interface AcpInstallStep {
  /** Why this step exists, in the user's terms. */
  purpose: string;
  /**
   * Exactly what is being run — **derived from `command` and `args`, never
   * written by hand.**
   *
   * This string is the consent: the modal shows it, and the user says yes to
   * what it says. A hand-maintained summary alongside the real argv drifts, and
   * it drifts in the dangerous direction — the first version of this read
   * `winget install --id OpenJS.NodeJS.LTS -e` while the argv also carried
   * `--accept-package-agreements --accept-source-agreements`, so the one detail
   * a user might have wanted to know (licence agreements accepted on their
   * behalf) was the detail the summary dropped. `formatCommandLine` removes the
   * possibility, and a test asserts every argument appears.
   */
  humanCommand: string;
  command: string;
  args: string[];
  /**
   * Resolve `command` to a real executable immediately before running it.
   *
   * Set on a step whose tool the *previous* step installs: npm does not exist
   * at planning time, so there is no path to resolve yet. Everything else is
   * resolved during planning, where a failure can still be reported as
   * "AtlasMind cannot do this" rather than as a mid-install crash.
   */
  resolveAtRunTime?: boolean;
}

/**
 * Render argv for display: the executable's name, then every argument verbatim.
 *
 * The resolved path is reduced to its basename — `/usr/bin/winget` tells the
 * user nothing `winget` does not — but no argument is ever summarised away.
 */
export function formatCommandLine(command: string, args: readonly string[]): string {
  const name = command.split(/[\\/]/).pop() || command;
  return [name, ...args].join(' ');
}

export type AcpInstallPlan =
  /** The agent is already on PATH; nothing to do. */
  | { status: 'ready' }
  | { status: 'plannable'; agentId: string; agentCommand: string; displayName: string; steps: AcpInstallStep[] }
  /**
   * Cannot be planned on this machine — no supported package manager, or an
   * agent AtlasMind has no install recipe for. The caller shows the manual
   * instruction instead of a button that would fail.
   */
  | { status: 'manual'; reason: string; humanCommand?: string };

interface RuntimeInstallOption {
  packageManager: RecommendedRuntimePackageManager;
  packageId: string;
  extraPackages?: string[];
  displayName: string;
}

interface AcpAgentRecipe {
  agentCommand: string;
  displayName: string;
  /** The tool that installs the agent, and how to install *that* if missing. */
  prerequisite: {
    command: string;
    displayName: string;
    installs: Partial<Record<SupportedRuntimePlatform, RuntimeInstallOption[]>>;
  };
  install: { command: string; args: string[] };
}

const NODE_INSTALLS: Partial<Record<SupportedRuntimePlatform, RuntimeInstallOption[]>> = {
  win32: [{ packageManager: 'winget', packageId: 'OpenJS.NodeJS.LTS', displayName: 'Node.js LTS' }],
  darwin: [{ packageManager: 'brew', packageId: 'node', displayName: 'Node.js' }],
  linux: [
    { packageManager: 'apt-get', packageId: 'nodejs', extraPackages: ['npm'], displayName: 'Node.js and npm' },
    { packageManager: 'dnf', packageId: 'nodejs', extraPackages: ['npm'], displayName: 'Node.js and npm' },
    { packageManager: 'pacman', packageId: 'nodejs', extraPackages: ['npm'], displayName: 'Node.js and npm' },
    { packageManager: 'brew', packageId: 'node', displayName: 'Node.js' },
  ],
};

/**
 * Rust, for `cargo install codex-acp`.
 *
 * Rust's own documented installer is a `curl … | sh` one-liner. It is not here
 * and will not be: piping a downloaded script into a shell is the exact thing
 * this module exists to avoid, and doing it *on the user's behalf* would be
 * worse than the dead end it replaces. Where a distribution packages cargo, that
 * package is used; where none does, the plan reports `manual` and the user is
 * shown rustup's own instructions to follow themselves.
 */
const CARGO_INSTALLS: Partial<Record<SupportedRuntimePlatform, RuntimeInstallOption[]>> = {
  win32: [{ packageManager: 'winget', packageId: 'Rustlang.Rustup', displayName: 'Rust (rustup)' }],
  darwin: [{ packageManager: 'brew', packageId: 'rust', displayName: 'Rust' }],
  linux: [
    { packageManager: 'apt-get', packageId: 'cargo', displayName: 'Rust (cargo)' },
    { packageManager: 'dnf', packageId: 'cargo', displayName: 'Rust (cargo)' },
    { packageManager: 'pacman', packageId: 'rust', displayName: 'Rust' },
    { packageManager: 'brew', packageId: 'rust', displayName: 'Rust' },
  ],
};

/**
 * How AtlasMind installs each agent it names.
 *
 * Only agents whose install command is *published by their vendor* appear here,
 * the same rule `VERIFIED_ACP_AGENTS` follows. A guessed install command is
 * worse than none: it fails in a way the user cannot diagnose, having been told
 * AtlasMind was handling it.
 */
const ACP_AGENT_RECIPES: Readonly<Record<string, AcpAgentRecipe>> = {
  claude: {
    agentCommand: 'claude-agent-acp',
    displayName: 'Claude Code ACP adapter',
    prerequisite: { command: 'npm', displayName: 'Node.js (npm)', installs: NODE_INSTALLS },
    install: {
      command: 'npm',
      args: ['install', '-g', '@zed-industries/claude-code-acp'],
    },
  },
  codex: {
    agentCommand: 'codex-acp',
    displayName: 'Codex ACP adapter',
    prerequisite: { command: 'cargo', displayName: 'Rust (cargo)', installs: CARGO_INSTALLS },
    install: {
      command: 'cargo',
      args: ['install', 'codex-acp'],
    },
  },
};

export interface AcpInstallProbe {
  platform: string;
  /** Resolves a command to an absolute path, or undefined when absent. */
  findExecutable: (command: string) => string | undefined;
  /**
   * Whether a path exists. Used only to go around Windows `.cmd` shims; falls
   * back to a real filesystem check when the caller does not supply one.
   */
  fileExists?: (path: string) => boolean;
}

/**
 * Turn the recipe's command into something that can actually be spawned.
 *
 * Two Windows facts made the first version fail with `spawn npm ENOENT`, and
 * both had to be handled:
 *
 * 1. **A bare name is not resolved.** `execFile('npm', …)` does not apply
 *    `PATHEXT`, so it looks for a file literally called `npm` and misses
 *    `npm.cmd`. The command has to be resolved to a full path first.
 * 2. **A resolved `.cmd` still cannot be spawned.** Since the fix for
 *    CVE-2024-27980, Node refuses to spawn `.cmd`/`.bat` without `shell: true`
 *    — and a shell is not on the table here, so the batch shim has to be
 *    bypassed rather than invoked.
 *
 * npm's shim wraps `node_modules/npm/bin/npm-cli.js`, sitting beside the
 * `node.exe` that runs it, so calling that script with Node directly does
 * exactly what the shim would have while staying a plain process spawn. When
 * that layout is not found the plan degrades to `manual` — running it in a
 * terminal is a small ask; guessing at an interpreter is not.
 */
function resolveSpawnable(
  command: string,
  args: readonly string[],
  probe: AcpInstallProbe,
): { command: string; args: string[] } | undefined {
  const resolved = probe.findExecutable(command);
  if (!resolved) {
    return undefined;
  }
  if (probe.platform !== 'win32' || !/\.(cmd|bat)$/i.test(resolved)) {
    return { command: resolved, args: [...args] };
  }

  const directory = resolved.slice(0, Math.max(resolved.lastIndexOf('\\'), resolved.lastIndexOf('/')));
  const exists = probe.fileExists ?? ((path: string) => existsSync(path));
  const node = `${directory}\\node.exe`;
  const script = WINDOWS_SHIM_SCRIPTS[command];
  if (!script) {
    return undefined;
  }
  const scriptPath = `${directory}\\${script}`;
  return exists(node) && exists(scriptPath)
    ? { command: node, args: [scriptPath, ...args] }
    : undefined;
}

/** Where a Windows batch shim's real entry point lives, relative to the shim. */
const WINDOWS_SHIM_SCRIPTS: Readonly<Record<string, string>> = {
  npm: 'node_modules\\npm\\bin\\npm-cli.js',
};

/**
 * Work out what would have to run for this agent to exist. Performs nothing.
 *
 * The runtime step is included **only when the runtime is actually missing**, so
 * a user who already has Node sees one command rather than a list that implies
 * AtlasMind is about to reinstall their toolchain.
 */
export function planAcpAgentInstall(agentId: string, probe: AcpInstallProbe): AcpInstallPlan {
  const recipe = ACP_AGENT_RECIPES[agentId];
  if (!recipe) {
    return {
      status: 'manual',
      reason: 'AtlasMind has no install recipe for this agent — it was named by you rather than taken from the published list, so only its own documentation knows how to install it.',
    };
  }

  if (probe.findExecutable(recipe.agentCommand)) {
    return { status: 'ready' };
  }

  const steps: AcpInstallStep[] = [];

  if (!probe.findExecutable(recipe.prerequisite.command)) {
    const runtimeStep = planRuntimeStep(recipe, probe);
    if (!runtimeStep) {
      return {
        status: 'manual',
        reason: `${recipe.displayName} is installed with ${recipe.prerequisite.command}, which is not on this machine, and AtlasMind found no supported package manager to install ${recipe.prerequisite.displayName} with.`,
        humanCommand: formatCommandLine(recipe.install.command, recipe.install.args),
      };
    }
    steps.push(runtimeStep);
    // The runtime is not installed *yet*, so its own command cannot be resolved
    // to a path now. Spawning it by name is what failed before, so the agent
    // step is planned by name only when it will exist by the time it runs, and
    // resolved at execution instead — see `runAcpInstallPlan`.
    steps.push({
      purpose: `Install the ${recipe.displayName}`,
      humanCommand: formatCommandLine(recipe.install.command, recipe.install.args),
      command: recipe.install.command,
      args: [...recipe.install.args],
      resolveAtRunTime: true,
    });
    return { status: 'plannable', agentId, agentCommand: recipe.agentCommand, displayName: recipe.displayName, steps };
  }

  const invocation = resolveSpawnable(recipe.install.command, recipe.install.args, probe);
  if (!invocation) {
    return {
      status: 'manual',
      reason: `${recipe.prerequisite.command} is installed, but AtlasMind could not work out how to run it directly on this system, so it will not guess.`,
      humanCommand: formatCommandLine(recipe.install.command, recipe.install.args),
    };
  }

  steps.push({
    purpose: `Install the ${recipe.displayName}`,
    // Shown as the command the user knows, not the internal path it resolves
    // to — but the arguments are the real ones, and the resolved target is
    // reported in the progress log when it differs.
    humanCommand: formatCommandLine(recipe.install.command, recipe.install.args),
    command: invocation.command,
    args: invocation.args,
  });

  return {
    status: 'plannable',
    agentId,
    agentCommand: recipe.agentCommand,
    displayName: recipe.displayName,
    steps,
  };
}

function planRuntimeStep(recipe: AcpAgentRecipe, probe: AcpInstallProbe): AcpInstallStep | undefined {
  const platform = (probe.platform === 'win32' || probe.platform === 'darwin' || probe.platform === 'linux')
    ? probe.platform
    : undefined;
  if (!platform) {
    return undefined;
  }

  for (const option of recipe.prerequisite.installs[platform] ?? []) {
    const executable = probe.findExecutable(option.packageManager);
    if (!executable) {
      continue;
    }
    const invocation = buildRuntimeInstallInvocation(
      executable,
      option.packageManager,
      option.packageId,
      option.extraPackages ?? [],
    );
    return {
      purpose: `Install ${option.displayName}, which ${recipe.displayName} needs`,
      // Rendered from the invocation actually built, so what is shown and what
      // runs cannot differ — including `sudo -n`, which appears only on the
      // platforms and privilege levels where it is genuinely used.
      humanCommand: formatCommandLine(invocation.command, invocation.args),
      command: invocation.command,
      args: invocation.args,
    };
  }
  return undefined;
}

export interface AcpInstallOutcome {
  ok: boolean;
  message: string;
  /** Steps that completed, for the log. */
  completed: string[];
}

/**
 * Run a confirmed plan, in order, stopping at the first failure.
 *
 * Stopping matters: the steps are a chain, and running `npm install` after Node
 * failed to install produces a second, more confusing error on top of the real
 * one. The message names the step that actually broke.
 *
 * Success is verified by the agent command resolving afterwards, not by exit
 * codes — a package manager can report success while putting the binary
 * somewhere this process's PATH will not find until the window is reloaded, and
 * saying "installed" to someone for whom nothing then works is the failure this
 * whole module is trying to avoid.
 */
export async function runAcpInstallPlan(
  plan: Extract<AcpInstallPlan, { status: 'plannable' }>,
  probe: AcpInstallProbe,
  onProgress?: (message: string) => void,
  exec: (command: string, args: string[]) => Promise<unknown> = execFileAsync,
): Promise<AcpInstallOutcome> {
  const completed: string[] = [];

  for (const step of plan.steps) {
    onProgress?.(`${step.purpose}…  (${step.humanCommand})`);

    let command = step.command;
    let args = step.args;
    if (step.resolveAtRunTime) {
      // The tool this step uses was installed by the step before it, so it
      // could not be resolved earlier. A freshly installed npm is also the case
      // most likely to be a `.cmd` this process cannot spawn directly.
      const invocation = resolveSpawnable(step.command, step.args, probe);
      if (!invocation) {
        return {
          ok: false,
          completed,
          message: `\`${step.command}\` was installed, but this window cannot run it yet — a new install is often not on PATH until the window reloads.\n\n`
            + `Reload the window and try again, or run this in a terminal:\n\n  ${step.humanCommand}`,
        };
      }
      command = invocation.command;
      args = invocation.args;
    }

    try {
      await exec(command, args);
      completed.push(step.humanCommand);
    } catch (error) {
      return {
        ok: false,
        completed,
        message: `This step did not complete:\n\n  ${step.humanCommand}\n\n${error instanceof Error ? error.message : String(error)}`,
      };
    }
  }

  if (!probe.findExecutable(plan.agentCommand)) {
    return {
      ok: false,
      completed,
      message: `The install commands ran without error, but \`${plan.agentCommand}\` still is not on this window's PATH. `
        + 'That usually means it landed somewhere PATH picks up only for new processes — reload the window and check again.',
    };
  }

  return {
    ok: true,
    completed,
    message: `${plan.displayName} is installed and \`${plan.agentCommand}\` is on PATH.`,
  };
}
