/**
 * Planning the install of an ACP agent — including the runtime it needs.
 *
 * "Install it with `npm install -g …`" is only useful advice if you have npm.
 * A novice reaching ACP through "use the Claude subscription I already pay for"
 * has no reason to have Node, and telling them to install an adapter with a
 * tool they do not have is a dead end dressed as an instruction.
 *
 * This plans the whole chain — runtime first, then the agent — and hands the
 * caller a list of commands to confirm. It is the same shape
 * `src/mcp/mcpRuntime.ts` already uses for MCP stdio runtimes, and deliberately
 * so: that pattern is the project's settled answer to "may AtlasMind install
 * something", and the answer is *only after showing exactly what will run and
 * being told yes*.
 *
 * Three properties make that answer safe, and all three are load-bearing:
 *
 * 1. **Every command is code-authored.** The argv below is a constant in this
 *    file. Nothing is parsed out of a documentation page, generated by a model,
 *    or assembled from a settings string. A command derived from fetched text
 *    and then executed is remote code execution with extra steps —
 *    `buzzDocsSource.ts` treats fetched commands as quoted suggestions AtlasMind
 *    never runs, and the same line holds here.
 * 2. **No shell.** Steps are `execFile(command, args)`, never a script and never
 *    a string passed through `sh -c`, so there is no interpolation to escape.
 * 3. **Planning performs nothing.** `planAcpAgentInstall` only inspects and
 *    returns; execution is a separate call the caller makes after confirmation.
 *
 * Pure apart from the injected probe, so every branch is unit-tested.
 */

import { buildRuntimeInstallInvocation, execFileAsync } from '../mcp/mcpRuntime.js';
import type { RecommendedRuntimePackageManager, SupportedRuntimePlatform } from '../constants.js';

/** One command AtlasMind proposes to run, shown verbatim before anything runs. */
export interface AcpInstallStep {
  /** Why this step exists, in the user's terms. */
  purpose: string;
  /** Exactly what is being run, for the confirmation dialog. */
  humanCommand: string;
  command: string;
  args: string[];
}

export type AcpInstallPlan =
  /** The agent is already on PATH; nothing to do. */
  | { status: 'ready' }
  | { status: 'plannable'; agentId: string; agentCommand: string; displayName: string; steps: AcpInstallStep[] }
  /**
   * Cannot be planned on this machine — no supported package manager, or an
   * agent AtlasMind has no install recipe for. The caller shows the manual
   * instruction instead of a button that would fail.
   */
  | { status: 'manual'; reason: string; humanCommand?: string };

interface RuntimeInstallOption {
  packageManager: RecommendedRuntimePackageManager;
  packageId: string;
  extraPackages?: string[];
  displayName: string;
}

interface AcpAgentRecipe {
  agentCommand: string;
  displayName: string;
  /** The tool that installs the agent, and how to install *that* if missing. */
  prerequisite: {
    command: string;
    displayName: string;
    installs: Partial<Record<SupportedRuntimePlatform, RuntimeInstallOption[]>>;
  };
  install: { command: string; args: string[]; humanCommand: string };
}

const NODE_INSTALLS: Partial<Record<SupportedRuntimePlatform, RuntimeInstallOption[]>> = {
  win32: [{ packageManager: 'winget', packageId: 'OpenJS.NodeJS.LTS', displayName: 'Node.js LTS' }],
  darwin: [{ packageManager: 'brew', packageId: 'node', displayName: 'Node.js' }],
  linux: [
    { packageManager: 'apt-get', packageId: 'nodejs', extraPackages: ['npm'], displayName: 'Node.js and npm' },
    { packageManager: 'dnf', packageId: 'nodejs', extraPackages: ['npm'], displayName: 'Node.js and npm' },
    { packageManager: 'pacman', packageId: 'nodejs', extraPackages: ['npm'], displayName: 'Node.js and npm' },
    { packageManager: 'brew', packageId: 'node', displayName: 'Node.js' },
  ],
};

/**
 * Rust, for `cargo install codex-acp`.
 *
 * Rust's own documented installer is a `curl … | sh` one-liner. It is not here
 * and will not be: piping a downloaded script into a shell is the exact thing
 * this module exists to avoid, and doing it *on the user's behalf* would be
 * worse than the dead end it replaces. Where a distribution packages cargo, that
 * package is used; where none does, the plan reports `manual` and the user is
 * shown rustup's own instructions to follow themselves.
 */
const CARGO_INSTALLS: Partial<Record<SupportedRuntimePlatform, RuntimeInstallOption[]>> = {
  win32: [{ packageManager: 'winget', packageId: 'Rustlang.Rustup', displayName: 'Rust (rustup)' }],
  darwin: [{ packageManager: 'brew', packageId: 'rust', displayName: 'Rust' }],
  linux: [
    { packageManager: 'apt-get', packageId: 'cargo', displayName: 'Rust (cargo)' },
    { packageManager: 'dnf', packageId: 'cargo', displayName: 'Rust (cargo)' },
    { packageManager: 'pacman', packageId: 'rust', displayName: 'Rust' },
    { packageManager: 'brew', packageId: 'rust', displayName: 'Rust' },
  ],
};

/**
 * How AtlasMind installs each agent it names.
 *
 * Only agents whose install command is *published by their vendor* appear here,
 * the same rule `VERIFIED_ACP_AGENTS` follows. A guessed install command is
 * worse than none: it fails in a way the user cannot diagnose, having been told
 * AtlasMind was handling it.
 */
const ACP_AGENT_RECIPES: Readonly<Record<string, AcpAgentRecipe>> = {
  claude: {
    agentCommand: 'claude-agent-acp',
    displayName: 'Claude Code ACP adapter',
    prerequisite: { command: 'npm', displayName: 'Node.js (npm)', installs: NODE_INSTALLS },
    install: {
      command: 'npm',
      args: ['install', '-g', '@zed-industries/claude-code-acp'],
      humanCommand: 'npm install -g @zed-industries/claude-code-acp',
    },
  },
  codex: {
    agentCommand: 'codex-acp',
    displayName: 'Codex ACP adapter',
    prerequisite: { command: 'cargo', displayName: 'Rust (cargo)', installs: CARGO_INSTALLS },
    install: {
      command: 'cargo',
      args: ['install', 'codex-acp'],
      humanCommand: 'cargo install codex-acp',
    },
  },
};

export interface AcpInstallProbe {
  platform: string;
  /** Resolves a command to an absolute path, or undefined when absent. */
  findExecutable: (command: string) => string | undefined;
}

/**
 * Work out what would have to run for this agent to exist. Performs nothing.
 *
 * The runtime step is included **only when the runtime is actually missing**, so
 * a user who already has Node sees one command rather than a list that implies
 * AtlasMind is about to reinstall their toolchain.
 */
export function planAcpAgentInstall(agentId: string, probe: AcpInstallProbe): AcpInstallPlan {
  const recipe = ACP_AGENT_RECIPES[agentId];
  if (!recipe) {
    return {
      status: 'manual',
      reason: 'AtlasMind has no install recipe for this agent — it was named by you rather than taken from the published list, so only its own documentation knows how to install it.',
    };
  }

  if (probe.findExecutable(recipe.agentCommand)) {
    return { status: 'ready' };
  }

  const steps: AcpInstallStep[] = [];

  if (!probe.findExecutable(recipe.prerequisite.command)) {
    const runtimeStep = planRuntimeStep(recipe, probe);
    if (!runtimeStep) {
      return {
        status: 'manual',
        reason: `${recipe.displayName} is installed with ${recipe.prerequisite.command}, which is not on this machine, and AtlasMind found no supported package manager to install ${recipe.prerequisite.displayName} with.`,
        humanCommand: recipe.install.humanCommand,
      };
    }
    steps.push(runtimeStep);
  }

  steps.push({
    purpose: `Install the ${recipe.displayName}`,
    humanCommand: recipe.install.humanCommand,
    command: recipe.install.command,
    args: [...recipe.install.args],
  });

  return {
    status: 'plannable',
    agentId,
    agentCommand: recipe.agentCommand,
    displayName: recipe.displayName,
    steps,
  };
}

function planRuntimeStep(recipe: AcpAgentRecipe, probe: AcpInstallProbe): AcpInstallStep | undefined {
  const platform = (probe.platform === 'win32' || probe.platform === 'darwin' || probe.platform === 'linux')
    ? probe.platform
    : undefined;
  if (!platform) {
    return undefined;
  }

  for (const option of recipe.prerequisite.installs[platform] ?? []) {
    const executable = probe.findExecutable(option.packageManager);
    if (!executable) {
      continue;
    }
    const invocation = buildRuntimeInstallInvocation(
      executable,
      option.packageManager,
      option.packageId,
      option.extraPackages ?? [],
    );
    return {
      purpose: `Install ${option.displayName}, which ${recipe.displayName} needs`,
      humanCommand: humanRuntimeCommand(option),
      command: invocation.command,
      args: invocation.args,
    };
  }
  return undefined;
}

function humanRuntimeCommand(option: RuntimeInstallOption): string {
  const packages = [option.packageId, ...(option.extraPackages ?? [])].join(' ');
  switch (option.packageManager) {
    case 'winget': return `winget install --id ${option.packageId} -e`;
    case 'brew': return `brew install ${packages}`;
    case 'apt-get': return `sudo apt-get install -y ${packages}`;
    case 'dnf': return `sudo dnf install -y ${packages}`;
    case 'pacman': return `sudo pacman -S --noconfirm ${packages}`;
  }
}

export interface AcpInstallOutcome {
  ok: boolean;
  message: string;
  /** Steps that completed, for the log. */
  completed: string[];
}

/**
 * Run a confirmed plan, in order, stopping at the first failure.
 *
 * Stopping matters: the steps are a chain, and running `npm install` after Node
 * failed to install produces a second, more confusing error on top of the real
 * one. The message names the step that actually broke.
 *
 * Success is verified by the agent command resolving afterwards, not by exit
 * codes — a package manager can report success while putting the binary
 * somewhere this process's PATH will not find until the window is reloaded, and
 * saying "installed" to someone for whom nothing then works is the failure this
 * whole module is trying to avoid.
 */
export async function runAcpInstallPlan(
  plan: Extract<AcpInstallPlan, { status: 'plannable' }>,
  probe: AcpInstallProbe,
  onProgress?: (message: string) => void,
  exec: (command: string, args: string[]) => Promise<unknown> = execFileAsync,
): Promise<AcpInstallOutcome> {
  const completed: string[] = [];

  for (const step of plan.steps) {
    onProgress?.(`${step.purpose}…  (${step.humanCommand})`);
    try {
      await exec(step.command, step.args);
      completed.push(step.humanCommand);
    } catch (error) {
      return {
        ok: false,
        completed,
        message: `This step did not complete:\n\n  ${step.humanCommand}\n\n${error instanceof Error ? error.message : String(error)}`,
      };
    }
  }

  if (!probe.findExecutable(plan.agentCommand)) {
    return {
      ok: false,
      completed,
      message: `The install commands ran without error, but \`${plan.agentCommand}\` still is not on this window's PATH. `
        + 'That usually means it landed somewhere PATH picks up only for new processes — reload the window and check again.',
    };
  }

  return {
    ok: true,
    completed,
    message: `${plan.displayName} is installed and \`${plan.agentCommand}\` is on PATH.`,
  };
}
