/**
 * Planning the GitHub CLI install for local CI.
 *
 * The Runner view's help for a missing `gh` was "open the official page, then
 * restart VS Code" — accurate, and the longest detour in a flow that already
 * has five prerequisites. `acpInstaller.ts` and `mcp/mcpRuntime.ts` already
 * settled how AtlasMind may install something, so this is that pattern applied
 * to the one binary local CI cannot work without.
 *
 * The three properties that make it safe are inherited deliberately:
 *
 * 1. **Every command is code-authored.** The package ids below are constants in
 *    this file. Nothing is parsed from a documentation page, generated by a
 *    model, or built from a settings string — a command derived from fetched
 *    text and then executed is remote code execution with extra steps.
 * 2. **No shell.** Steps are `execFile(command, args)`, never a string through
 *    `sh -c`, so there is nothing to escape.
 * 3. **Planning performs nothing.** `planGitHubCliInstall` inspects and returns;
 *    running is a separate call the caller makes after showing every command.
 *
 * Two things are deliberately *not* here.
 *
 * **Docker is not installed by AtlasMind.** It is a system service with a
 * virtual machine behind it, frequently needing a reboot and group membership
 * changes, and on Windows and macOS its installer is interactive. A button that
 * half-works and leaves somebody with a broken engine is worse than the link
 * they would have clicked anyway. The Runner view keeps offering the official
 * page for it.
 *
 * **`apt-get` is not offered for `gh`.** `gh` is absent from the repositories
 * of Debian and Ubuntu releases still in wide use, and GitHub's own instruction
 * for those is to add a keyring and an apt source — a multi-step pipeline
 * fetching a key over the network, which is exactly the shape rule 1 exists to
 * refuse. Reporting `manual` with the official URL is the honest outcome; a
 * command that fails on most of a platform's machines teaches people the
 * feature is broken.
 *
 * Pure apart from the injected probe, so every branch is unit-tested.
 */

import { execFileAsync, buildRuntimeInstallInvocation } from '../mcp/mcpRuntime.js';
import type { RecommendedRuntimePackageManager, SupportedRuntimePlatform } from '../constants.js';

/** The command local CI needs on PATH. */
export const GITHUB_CLI_COMMAND = 'gh';
export const GITHUB_CLI_INSTALL_URL = 'https://github.com/cli/cli#installation';

/**
 * Reviewed package identifiers, per platform, in preference order.
 *
 * Constants, never parsed. On Linux `brew` comes first only because it needs no
 * elevation; the distribution managers follow. See the module comment for why
 * `apt-get` is absent.
 */
const GITHUB_CLI_PACKAGES: Readonly<Record<SupportedRuntimePlatform, ReadonlyArray<{
  packageManager: RecommendedRuntimePackageManager;
  packageId: string;
  displayName: string;
}>>> = {
  win32: [{ packageManager: 'winget', packageId: 'GitHub.cli', displayName: 'GitHub CLI' }],
  darwin: [{ packageManager: 'brew', packageId: 'gh', displayName: 'GitHub CLI' }],
  linux: [
    { packageManager: 'brew', packageId: 'gh', displayName: 'GitHub CLI' },
    { packageManager: 'dnf', packageId: 'gh', displayName: 'GitHub CLI' },
    { packageManager: 'pacman', packageId: 'github-cli', displayName: 'GitHub CLI' },
  ],
};

/** The executable that drives each package manager. */
const PACKAGE_MANAGER_COMMANDS: Readonly<Record<RecommendedRuntimePackageManager, string>> = {
  winget: 'winget',
  brew: 'brew',
  'apt-get': 'apt-get',
  dnf: 'dnf',
  pacman: 'pacman',
};

/** One command AtlasMind proposes to run, shown verbatim before anything runs. */
export interface LocalCiInstallStep {
  /** Why this step exists, in the user's terms. */
  purpose: string;
  /**
   * Exactly what will run — derived from `command` and `args`, never written by
   * hand. This string is the consent: a hand-maintained summary beside the real
   * argv drifts, and it drifts in the direction of dropping the detail somebody
   * would have wanted (licence agreements accepted on their behalf, say).
   */
  humanCommand: string;
  command: string;
  args: string[];
  /**
   * Needs administrator rights AtlasMind cannot obtain.
   *
   * `buildRuntimeInstallInvocation` elevates with `sudo -n` — non-interactive,
   * meaning *fail rather than prompt*, which is the only correct choice from an
   * extension host with no terminal to prompt in. Marked rather than attempted,
   * so the caller can show the command instead of a button that will fail for
   * everyone without passwordless sudo.
   */
  requiresElevation?: boolean;
}

export type LocalCiInstallPlan =
  /** Already on PATH; nothing to do. */
  | { status: 'ready' }
  | { status: 'plannable'; displayName: string; steps: LocalCiInstallStep[] }
  /** No supported package manager here. The caller shows the official page. */
  | { status: 'manual'; reason: string; url: string };

export interface LocalCiInstallProbe {
  platform: string;
  /** Resolve a command on PATH, or `undefined`. */
  findExecutable(command: string): string | undefined;
}

/** Render argv for display: the executable's name, then every argument verbatim. */
export function formatInstallCommand(command: string, args: readonly string[]): string {
  const name = command.split(/[\\/]/).pop() || command;
  return [name, ...args].join(' ');
}

function platformKey(platform: string): SupportedRuntimePlatform | undefined {
  return platform === 'win32' || platform === 'darwin' || platform === 'linux' ? platform : undefined;
}

/**
 * Work out how the GitHub CLI could be installed here, without installing it.
 *
 * Returns `ready` when `gh` already resolves, so the caller never offers to
 * install something present — the guide's own rule about not sending people to
 * install what they have.
 */
export function planGitHubCliInstall(probe: LocalCiInstallProbe): LocalCiInstallPlan {
  if (probe.findExecutable(GITHUB_CLI_COMMAND)) {
    return { status: 'ready' };
  }
  const key = platformKey(probe.platform);
  if (!key) {
    return {
      status: 'manual',
      reason: `AtlasMind has no reviewed install command for ${probe.platform}.`,
      url: GITHUB_CLI_INSTALL_URL,
    };
  }

  for (const candidate of GITHUB_CLI_PACKAGES[key]) {
    const managerExecutable = probe.findExecutable(PACKAGE_MANAGER_COMMANDS[candidate.packageManager]);
    if (!managerExecutable) {
      continue;
    }
    const invocation = buildRuntimeInstallInvocation(
      managerExecutable,
      candidate.packageManager,
      candidate.packageId,
    );
    const elevated = candidate.packageManager === 'dnf' || candidate.packageManager === 'pacman';
    return {
      status: 'plannable',
      displayName: candidate.displayName,
      steps: [{
        purpose: `Install the GitHub CLI with ${candidate.packageManager}`,
        humanCommand: formatInstallCommand(invocation.command, invocation.args),
        command: invocation.command,
        args: invocation.args,
        ...(elevated ? { requiresElevation: true } : {}),
      }],
    };
  }

  return {
    status: 'manual',
    reason: key === 'linux'
      // Named rather than generic: "no package manager found" is confusing on a
      // machine that plainly has apt, and the reason it is excluded is a
      // decision worth stating rather than looking like an oversight.
      ? 'No package manager AtlasMind has a reviewed GitHub CLI command for was found. Debian and Ubuntu are deliberately excluded: installing `gh` there means adding GitHub\'s apt repository and keyring, which AtlasMind will not script.'
      : `No supported package manager was found on this ${key === 'win32' ? 'Windows' : 'macOS'} machine.`,
    url: GITHUB_CLI_INSTALL_URL,
  };
}

export interface LocalCiInstallOutcome {
  ok: boolean;
  message: string;
  /** Steps that completed, for the log. */
  completed: string[];
}

/**
 * Run a confirmed plan, stopping at the first failure.
 *
 * Success is verified by `gh` resolving afterwards, **not** by exit codes. A
 * package manager can report success while putting the binary somewhere this
 * process's PATH will not see until the window reloads, and telling somebody
 * "installed" when nothing then works is the exact failure this module exists
 * to remove rather than relocate.
 */
export async function runGitHubCliInstallPlan(
  plan: Extract<LocalCiInstallPlan, { status: 'plannable' }>,
  probe: LocalCiInstallProbe,
  onProgress?: (message: string) => void,
  exec: (command: string, args: string[]) => Promise<unknown> = execFileAsync,
): Promise<LocalCiInstallOutcome> {
  const completed: string[] = [];
  for (const step of plan.steps) {
    onProgress?.(`${step.purpose}…  (${step.humanCommand})`);
    try {
      await exec(step.command, step.args);
      completed.push(step.humanCommand);
    } catch (error) {
      return {
        ok: false,
        completed,
        message: `This step did not complete:\n\n  ${step.humanCommand}\n\n${error instanceof Error ? error.message : String(error)}`,
      };
    }
  }

  if (!probe.findExecutable(GITHUB_CLI_COMMAND)) {
    return {
      ok: false,
      completed,
      message: 'The install ran without error, but `gh` is still not on this window\'s PATH. '
        + 'That usually means it landed somewhere PATH only picks up for new processes — reload the VS Code window, then inspect again.',
    };
  }

  return {
    ok: true,
    completed,
    message: `${plan.displayName} is installed and \`gh\` is on PATH. Sign in with \`gh auth login --hostname github.com --web\`, then inspect again.`,
  };
}
